;; -*-no-byte-compile: t; -*-

;; some custom settings done by hand, not autogenerated by emacs

(if (= emacs-major-version 24)
  (load-theme 'monokai)
  (color-theme-tomorrow-night-eighties))

(setq default-directory "~/code")

(provide 'custom)
